window_size: 17
train_split: 0.9
embedding_dim: 50
hidden_dim: 128
batch_size: 32
epochs: 30
dropout_rate: 0.4
learning_rate: 0.001
patience: 3
dataset_path: data/CB513.csv
esm_embeddings_path:  data/esm_embeddings
esm_model: facebook/esm2_t6_8M_UR50D
device: auto # cuda if possible else cpu
use_pretrained_embeddings: False
