window_size: 17
train_split: 0.9
embedding_dim: 50
hidden_dim: 128
batch_size: 32
epochs: 30
dropout_rate: 0.4
learning_rate: 0.001
patience: 3
checkpoint_path: checkpoints/best_model.pt
dataset_path: data/CB513.csv
device: auto # cuda if possible else cpu